### ISSUE TITLE
Checking if null never returns true.

### ISSUE THREAD

**Issue by HarveyWilliams** [DigitalMomentum/Umbraco7-Videolizer#2]
Hi, nice package.

However, when I use the following code, it always runs the if statement block:

```
@if (Model.Content.Video != null)
{
    <iframe width="100%" height="281" src="@(Model.Content.Video.embedUrl)" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
}
```

I'm using the Models Builder here to get typed content.

It feels like `Videolizer.VideolizerVideo` should be null if the user has not added a video. Instead I have to check to see if a property of this class is null.

**Comment by dinc5150** [comment]
Thanks for your feedback @HarveyWilliams 

I've deliberate over this, this morning and have decided to add a method to check instead of returning null. 

I've decided to do this to allow to use the simplified `@Model.Content.GetPropertyValue<VideolizerVideo>("video").GetSimpleEmbed()` without the need of always wrapping it in an if statement.

You will need to do the following to check:
`@if (Model.Content.Video.HasVideo())
{
    <iframe width="100%" height="281" src="@(Model.Content.Video.embedUrl)" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
}`

**Comment by HarveyWilliams** [comment]
@dinc5150 Looks like a good solution. Thanks for your work!
